services:
  web:
    build: .
    container_name: guestbook-web
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: guestbook_db
      MYSQL_USER: guest
      MYSQL_PASSWORD: guestpass
    ports:
      - "3307:3306"
